---
apiVersion: v1
kind: Pod
metadata:
  name: caddy-pod
  labels:
    app: caddy
spec:
  containers:
    - name: caddy
      image: vamsidharp/static-site-test:latest
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
      envFrom:
        - configMapRef:
            name: caddy-config
        - secretRef:
            name: caddy-secrets
  imagePullSecrets:
    - name: caddy-secrets
